#!/bin/bash

set -e

source script/setup-env $@

echo -e "🔨 ${BLUE}building in ${PURPLE}release${BLUE} mode${OFF}"
shards build --production --release --progress --debug --error-trace

docker run --rm -it -v $(pwd):/workspace -w /workspace crystallang/crystal:1.14.0 \
  shards build --production --release --progress --debug --error-trace

echo -e "📦 ${GREEN}build complete${OFF}"
